package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppAccountTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppAccountTypeAllPropertiesEquals(AppAccountType expected, AppAccountType actual) {
        assertAppAccountTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAppAccountTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppAccountTypeAllUpdatablePropertiesEquals(AppAccountType expected, AppAccountType actual) {
        assertAppAccountTypeUpdatableFieldsEquals(expected, actual);
        assertAppAccountTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppAccountTypeAutoGeneratedPropertiesEquals(AppAccountType expected, AppAccountType actual) {
        assertThat(expected)
            .as("Verify AppAccountType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppAccountTypeUpdatableFieldsEquals(AppAccountType expected, AppAccountType actual) {
        assertThat(expected)
            .as("Verify AppAccountType relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppAccountTypeUpdatableRelationshipsEquals(AppAccountType expected, AppAccountType actual) {
        assertThat(expected)
            .as("Verify AppAccountType relationships")
            .satisfies(e -> assertThat(e.getAppAccounts()).as("check appAccounts").isEqualTo(actual.getAppAccounts()));
    }
}
