package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTestTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTestTypeAllPropertiesEquals(AppTestType expected, AppTestType actual) {
        assertAppTestTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAppTestTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTestTypeAllUpdatablePropertiesEquals(AppTestType expected, AppTestType actual) {
        assertAppTestTypeUpdatableFieldsEquals(expected, actual);
        assertAppTestTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTestTypeAutoGeneratedPropertiesEquals(AppTestType expected, AppTestType actual) {
        assertThat(expected)
            .as("Verify AppTestType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTestTypeUpdatableFieldsEquals(AppTestType expected, AppTestType actual) {
        assertThat(expected)
            .as("Verify AppTestType relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTestTypeUpdatableRelationshipsEquals(AppTestType expected, AppTestType actual) {
        assertThat(expected)
            .as("Verify AppTestType relationships")
            .satisfies(e -> assertThat(e.getAppTests()).as("check appTests").isEqualTo(actual.getAppTests()));
    }
}
