package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContractTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractTypeAllPropertiesEquals(ContractType expected, ContractType actual) {
        assertContractTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertContractTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractTypeAllUpdatablePropertiesEquals(ContractType expected, ContractType actual) {
        assertContractTypeUpdatableFieldsEquals(expected, actual);
        assertContractTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractTypeAutoGeneratedPropertiesEquals(ContractType expected, ContractType actual) {
        assertThat(expected)
            .as("Verify ContractType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractTypeUpdatableFieldsEquals(ContractType expected, ContractType actual) {
        assertThat(expected)
            .as("Verify ContractType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractTypeUpdatableRelationshipsEquals(ContractType expected, ContractType actual) {
        assertThat(expected)
            .as("Verify ContractType relationships")
            .satisfies(e -> assertThat(e.getApplications()).as("check applications").isEqualTo(actual.getApplications()));
    }
}
