package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CriteriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriteriaAllPropertiesEquals(Criteria expected, Criteria actual) {
        assertCriteriaAutoGeneratedPropertiesEquals(expected, actual);
        assertCriteriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriteriaAllUpdatablePropertiesEquals(Criteria expected, Criteria actual) {
        assertCriteriaUpdatableFieldsEquals(expected, actual);
        assertCriteriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriteriaAutoGeneratedPropertiesEquals(Criteria expected, Criteria actual) {
        assertThat(expected)
            .as("Verify Criteria auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriteriaUpdatableFieldsEquals(Criteria expected, Criteria actual) {
        assertThat(expected)
            .as("Verify Criteria relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriteriaUpdatableRelationshipsEquals(Criteria expected, Criteria actual) {
        assertThat(expected)
            .as("Verify Criteria relationships")
            .satisfies(e -> assertThat(e.getApplications()).as("check applications").isEqualTo(actual.getApplications()));
    }
}
