package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecruiterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruiterAllPropertiesEquals(Recruiter expected, Recruiter actual) {
        assertRecruiterAutoGeneratedPropertiesEquals(expected, actual);
        assertRecruiterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruiterAllUpdatablePropertiesEquals(Recruiter expected, Recruiter actual) {
        assertRecruiterUpdatableFieldsEquals(expected, actual);
        assertRecruiterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruiterAutoGeneratedPropertiesEquals(Recruiter expected, Recruiter actual) {
        assertThat(expected)
            .as("Verify Recruiter auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruiterUpdatableFieldsEquals(Recruiter expected, Recruiter actual) {
        assertThat(expected)
            .as("Verify Recruiter relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(e -> assertThat(e.getProfileImage()).as("check profileImage").isEqualTo(actual.getProfileImage()))
            .satisfies(
                e ->
                    assertThat(e.getProfileImageContentType())
                        .as("check profileImage contenty type")
                        .isEqualTo(actual.getProfileImageContentType())
            )
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()))
            .satisfies(e -> assertThat(e.getLinkedinUrl()).as("check linkedinUrl").isEqualTo(actual.getLinkedinUrl()))
            .satisfies(e -> assertThat(e.getApprovedExperience()).as("check approvedExperience").isEqualTo(actual.getApprovedExperience()))
            .satisfies(e -> assertThat(e.getScore()).as("check score").isEqualTo(actual.getScore()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruiterUpdatableRelationshipsEquals(Recruiter expected, Recruiter actual) {
        assertThat(expected)
            .as("Verify Recruiter relationships")
            .satisfies(e -> assertThat(e.getWallet()).as("check wallet").isEqualTo(actual.getWallet()))
            .satisfies(e -> assertThat(e.getApplications()).as("check applications").isEqualTo(actual.getApplications()))
            .satisfies(e -> assertThat(e.getOperationalDomains()).as("check operationalDomains").isEqualTo(actual.getOperationalDomains()));
    }
}
