package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResumeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAllPropertiesEquals(Resume expected, Resume actual) {
        assertResumeAutoGeneratedPropertiesEquals(expected, actual);
        assertResumeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAllUpdatablePropertiesEquals(Resume expected, Resume actual) {
        assertResumeUpdatableFieldsEquals(expected, actual);
        assertResumeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeAutoGeneratedPropertiesEquals(Resume expected, Resume actual) {
        assertThat(expected)
            .as("Verify Resume auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeUpdatableFieldsEquals(Resume expected, Resume actual) {
        assertThat(expected)
            .as("Verify Resume relevant properties")
            .satisfies(e -> assertThat(e.getResume()).as("check resume").isEqualTo(actual.getResume()))
            .satisfies(e -> assertThat(e.getResumeContentType()).as("check resume contenty type").isEqualTo(actual.getResumeContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResumeUpdatableRelationshipsEquals(Resume expected, Resume actual) {
        assertThat(expected)
            .as("Verify Resume relationships")
            .satisfies(e -> assertThat(e.getOwner()).as("check owner").isEqualTo(actual.getOwner()));
    }
}
