package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TechCVProjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechCVProjectAllPropertiesEquals(TechCVProject expected, TechCVProject actual) {
        assertTechCVProjectAutoGeneratedPropertiesEquals(expected, actual);
        assertTechCVProjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechCVProjectAllUpdatablePropertiesEquals(TechCVProject expected, TechCVProject actual) {
        assertTechCVProjectUpdatableFieldsEquals(expected, actual);
        assertTechCVProjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechCVProjectAutoGeneratedPropertiesEquals(TechCVProject expected, TechCVProject actual) {
        assertThat(expected)
            .as("Verify TechCVProject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechCVProjectUpdatableFieldsEquals(TechCVProject expected, TechCVProject actual) {
        assertThat(expected)
            .as("Verify TechCVProject relevant properties")
            .satisfies(e -> assertThat(e.getProject()).as("check project").isEqualTo(actual.getProject()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechCVProjectUpdatableRelationshipsEquals(TechCVProject expected, TechCVProject actual) {
        assertThat(expected)
            .as("Verify TechCVProject relationships")
            .satisfies(e -> assertThat(e.getTechnicalCV()).as("check technicalCV").isEqualTo(actual.getTechnicalCV()));
    }
}
