package com.axone.hrsolution.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TechnicalCVAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalCVAllPropertiesEquals(TechnicalCV expected, TechnicalCV actual) {
        assertTechnicalCVAutoGeneratedPropertiesEquals(expected, actual);
        assertTechnicalCVAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalCVAllUpdatablePropertiesEquals(TechnicalCV expected, TechnicalCV actual) {
        assertTechnicalCVUpdatableFieldsEquals(expected, actual);
        assertTechnicalCVUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalCVAutoGeneratedPropertiesEquals(TechnicalCV expected, TechnicalCV actual) {
        assertThat(expected)
            .as("Verify TechnicalCV auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalCVUpdatableFieldsEquals(TechnicalCV expected, TechnicalCV actual) {
        assertThat(expected)
            .as("Verify TechnicalCV relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getLevel()).as("check level").isEqualTo(actual.getLevel()))
            .satisfies(e -> assertThat(e.getProfileDescription()).as("check profileDescription").isEqualTo(actual.getProfileDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTechnicalCVUpdatableRelationshipsEquals(TechnicalCV expected, TechnicalCV actual) {}
}
